from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.domain.content.entities import Article, Author, Category, Guest, StaticPage, Tag
from app.domain.content.value_objects import PublicationStatus


class PageRepository(Protocol):
    def get_by_id(self, page_id: uuid.UUID) -> StaticPage | None: ...
    def get_by_slug(self, slug: str) -> StaticPage | None: ...
    def list_all(self) -> list[StaticPage]: ...
    def save(self, page: StaticPage) -> None: ...


class AuthorRepository(Protocol):
    def add(self, author: Author) -> None: ...
    def get_by_id(self, author_id: uuid.UUID) -> Author | None: ...
    def get_by_slug(self, slug: str) -> Author | None: ...
    def get_by_user_id(self, user_id: uuid.UUID) -> Author | None: ...
    def list_all(self) -> list[Author]: ...
    def save(self, author: Author) -> None: ...
    def delete(self, author_id: uuid.UUID) -> None: ...


class TagRepository(Protocol):
    def get_by_id(self, tag_id: uuid.UUID) -> Tag | None: ...
    def get_by_slug(self, slug: str) -> Tag | None: ...
    def get_or_create(self, name: str) -> Tag: ...
    def list_all(self) -> list[Tag]: ...
    def get_by_article(self, article_id: uuid.UUID) -> list[Tag]: ...
    def set_article_tags(self, article_id: uuid.UUID, tag_ids: list[uuid.UUID]) -> None: ...
    def delete(self, tag_id: uuid.UUID) -> None: ...


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def get_by_id(self, category_id: uuid.UUID) -> Category | None: ...
    def get_by_slug(self, slug: str) -> Category | None: ...
    def list_all(self) -> list[Category]: ...
    def save(self, category: Category) -> None: ...
    def delete(self, category_id: uuid.UUID) -> None: ...


class GuestRepository(Protocol):
    def add(self, guest: Guest) -> None: ...
    def get_by_id(self, guest_id: uuid.UUID) -> Guest | None: ...
    def get_by_slug(self, slug: str) -> Guest | None: ...
    def list_all(self) -> list[Guest]: ...
    def save(self, guest: Guest) -> None: ...
    def delete(self, guest_id: uuid.UUID) -> None: ...
    def get_by_article(self, article_id: uuid.UUID) -> list[Guest]: ...
    def set_article_guests(self, article_id: uuid.UUID, guest_ids: list[uuid.UUID]) -> None: ...


class ArticleRepository(Protocol):
    def add(self, article: Article) -> None: ...
    def get_by_id(self, article_id: uuid.UUID) -> Article | None: ...
    def get_by_slug(self, slug: str) -> Article | None: ...
    def get_by_preview_token(self, token: uuid.UUID) -> Article | None: ...
    def save(self, article: Article) -> None: ...
    def list_all(
        self,
        *,
        author_id: uuid.UUID | None = None,
        status: PublicationStatus | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[Article], int]: ...
    def list_published(
        self,
        *,
        before: datetime,
        category_id: uuid.UUID | None = None,
        tag_id: uuid.UUID | None = None,
        author_profile_id: uuid.UUID | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[Article], int]: ...
    def list_published_by_guest(
        self,
        *,
        guest_id: uuid.UUID,
        before: datetime,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[Article], int]: ...
