from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.domain.content.entities import Article, Category
from app.domain.content.value_objects import PublicationStatus


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def get_by_id(self, category_id: uuid.UUID) -> Category | None: ...
    def get_by_slug(self, slug: str) -> Category | None: ...
    def list_all(self) -> list[Category]: ...
    def save(self, category: Category) -> None: ...
    def delete(self, category_id: uuid.UUID) -> None: ...


class ArticleRepository(Protocol):
    def add(self, article: Article) -> None: ...
    def get_by_id(self, article_id: uuid.UUID) -> Article | None: ...
    def get_by_slug(self, slug: str) -> Article | None: ...
    def get_by_preview_token(self, token: uuid.UUID) -> Article | None: ...
    def save(self, article: Article) -> None: ...
    def list_all(
        self,
        *,
        author_id: uuid.UUID | None = None,
        status: PublicationStatus | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[Article], int]: ...
    def list_published(
        self,
        *,
        before: datetime,
        category_id: uuid.UUID | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[Article], int]: ...
