"""Abstract repository interfaces for the identity domain (protocol-based)."""

import uuid
from datetime import datetime
from typing import Protocol

from app.domain.identity.entities import RefreshToken, User
from app.domain.identity.value_objects import Email


class UserRepository(Protocol):
    def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    def get_by_email(self, email: Email) -> User | None: ...
    def save(self, user: User) -> None: ...
    def add(self, user: User) -> None: ...


class RefreshTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    def add(self, token: RefreshToken) -> None: ...
    def revoke(self, token_id: uuid.UUID, now: datetime) -> None: ...
    def revoke_all_for_user(self, user_id: uuid.UUID, now: datetime) -> None: ...
